# Generated by Django 5.2.17 on 2026-09-28 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'En attente'), ('running', 'En cours'), ('succeeded', 'Terminé'), ('failed', 'Échec')], db_index=True, default='queued', max_length=16)),
                ('queue_task_id', models.CharField(blank=True, max_length=32)),
                ('process_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mvola_reconciliation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('view_mvola_reconciliation_runs', 'Can view MVOLA reconciliation runs')],
            },
        ),
    ]
