# Generated by Django 5.2.17 on 2026-09-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteropMvolaCbs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('api_log_id', models.TextField(blank=True, db_column='apiLogId', null=True)),
                ('posting_date', models.TextField(blank=True, db_column='PostingDate', null=True)),
                ('amount_cry', models.FloatField(blank=True, db_column='AmountCRY', null=True)),
                ('trx_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interop_mvola_cbs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InteropMvolaMvola',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_trans', models.TextField(blank=True, db_column='DATE_TRANS', null=True)),
                ('transid_mvola', models.TextField(blank=True, db_column='TRANSID_MVOLA', null=True)),
                ('state', models.TextField(blank=True, db_column='STATE', null=True)),
                ('msisdn', models.TextField(blank=True, db_column='MSISDN', null=True)),
                ('pivot', models.BigIntegerField(blank=True, db_column='PIVOT', null=True)),
                ('sens', models.TextField(blank=True, db_column='SENS', null=True)),
                ('nom', models.TextField(blank=True, db_column='NOM', null=True)),
                ('transid_parent', models.BigIntegerField(blank=True, db_column='TRANSID_PARENT', null=True)),
                ('trans_type', models.TextField(blank=True, db_column='TRANS_TYPE', null=True)),
                ('amount', models.BigIntegerField(blank=True, db_column='AMOUNT', null=True)),
                ('solde_pivot_avant', models.BigIntegerField(blank=True, db_column='SOLDE_PIVOT_AVANT', null=True)),
                ('solde_pivot_apres', models.BigIntegerField(blank=True, db_column='SOLDE_PIVOT_APRES', null=True)),
                ('origftid', models.TextField(blank=True, db_column='ORIGFTID', null=True)),
                ('type_operation', models.TextField(blank=True, db_column='TYPE_OPERATION', null=True)),
            ],
            options={
                'db_table': 'interop_mvola_mvola',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InteropMvolaProcess',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(db_column='userID')),
                ('status', models.TextField(db_column='Status')),
                ('insert_date', models.DateTimeField(db_column='insertDate')),
                ('transaction_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interop_mvola_process',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InteropMvolaReconciliation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_trans', models.TextField(blank=True, db_column='DATE_TRANS', null=True)),
                ('transid_mvola', models.TextField(blank=True, db_column='TRANSID_MVOLA', null=True)),
                ('state', models.TextField(blank=True, db_column='STATE', null=True)),
                ('msisdn', models.TextField(blank=True, db_column='MSISDN', null=True)),
                ('pivot', models.BigIntegerField(blank=True, db_column='PIVOT', null=True)),
                ('sens', models.TextField(blank=True, db_column='SENS', null=True)),
                ('nom', models.TextField(blank=True, db_column='NOM', null=True)),
                ('transid_parent', models.BigIntegerField(blank=True, db_column='TRANSID_PARENT', null=True)),
                ('trans_type', models.TextField(blank=True, db_column='TRANS_TYPE', null=True)),
                ('amount', models.BigIntegerField(blank=True, db_column='AMOUNT', null=True)),
                ('solde_pivot_avant', models.BigIntegerField(blank=True, db_column='SOLDE_PIVOT_AVANT', null=True)),
                ('solde_pivot_apres', models.BigIntegerField(blank=True, db_column='SOLDE_PIVOT_APRES', null=True)),
                ('origftid', models.TextField(blank=True, db_column='ORIGFTID', null=True)),
                ('type_operation', models.TextField(blank=True, db_column='TYPE_OPERATION', null=True)),
                ('api_log_id', models.TextField(blank=True, db_column='apiLogId', null=True)),
                ('posting_date', models.TextField(blank=True, db_column='PostingDate', null=True)),
                ('amount_cry', models.FloatField(blank=True, db_column='AmountCRY', null=True)),
                ('trx_id', models.TextField(blank=True, null=True)),
                ('reconciliation_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interop_mvola_reconciliation',
                'managed': False,
            },
        ),
    ]
