# Generated by Django 5.2.17 on 2026-09-28 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvola', '0002_interopmvolacbs_interopmvolamvola_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanMvolaProcessingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('is_retried', models.BooleanField(default=False)),
                ('response_message', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('orphan_mvola', 'Orphan mvola'), ('orphan_pamf', 'Orphan pamf'), ('processing', 'Processing'), ('done', 'Done')], max_length=16)),
                ('comments', models.TextField(blank=True)),
                ('InteropMvolaReconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orphan_processing_history', to='mvola.interopmvolareconciliation')),
            ],
        ),
    ]
