# Generated by Django 5.2.17 on 2026-09-30 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InteropOmCbs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "api_log_id",
                    models.TextField(blank=True, db_column="apiLogId", null=True),
                ),
                (
                    "posting_date",
                    models.TextField(blank=True, db_column="PostingDate", null=True),
                ),
                (
                    "amount_cry",
                    models.FloatField(blank=True, db_column="AmountCRY", null=True),
                ),
                ("trx_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "interop_om_cbs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InteropOmOm",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("no", models.BigIntegerField(blank=True, db_column="No", null=True)),
                ("date", models.TextField(blank=True, null=True)),
                ("hour", models.TextField(blank=True, null=True)),
                ("trx_id", models.TextField(blank=True, null=True)),
                ("service", models.TextField(blank=True, null=True)),
                ("transaction_type", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("mode", models.TextField(blank=True, null=True)),
                ("technical_account", models.TextField(blank=True, null=True)),
                ("wallet_technical_account", models.TextField(blank=True, null=True)),
                ("pseudo", models.TextField(blank=True, null=True)),
                ("client_account", models.TextField(blank=True, null=True)),
                ("wallet_type", models.TextField(blank=True, null=True)),
                ("debit", models.TextField(blank=True, null=True)),
                ("credit", models.TextField(blank=True, null=True)),
                ("commission_amount", models.BigIntegerField(blank=True, null=True)),
                ("sous_reseau", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "interop_om_om",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InteropOmProcess",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField(db_column="userID")),
                ("status", models.TextField(db_column="Status")),
                ("insert_date", models.DateTimeField(db_column="insertDate")),
                ("transaction_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "interop_om_process",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InteropOmReconciliation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("no", models.BigIntegerField(blank=True, db_column="No", null=True)),
                ("date", models.TextField(blank=True, null=True)),
                ("hour", models.TextField(blank=True, null=True)),
                ("trx_id", models.TextField(blank=True, null=True)),
                ("service", models.TextField(blank=True, null=True)),
                ("transaction_type", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("mode", models.TextField(blank=True, null=True)),
                ("technical_account", models.TextField(blank=True, null=True)),
                ("wallet_technical_account", models.TextField(blank=True, null=True)),
                ("pseudo", models.TextField(blank=True, null=True)),
                ("client_account", models.TextField(blank=True, null=True)),
                ("wallet_type", models.TextField(blank=True, null=True)),
                ("debit", models.TextField(blank=True, null=True)),
                ("credit", models.TextField(blank=True, null=True)),
                ("commission_amount", models.BigIntegerField(blank=True, null=True)),
                ("sous_reseau", models.BigIntegerField(blank=True, null=True)),
                (
                    "api_log_id",
                    models.TextField(blank=True, db_column="apiLogId", null=True),
                ),
                (
                    "posting_date",
                    models.TextField(blank=True, db_column="PostingDate", null=True),
                ),
                (
                    "amount_cry",
                    models.FloatField(blank=True, db_column="AmountCRY", null=True),
                ),
                ("reconciliation_status", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "interop_om_reconciliation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrphanOmProcessingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("is_retried", models.BooleanField(default=False)),
                ("response_message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("orphan_om", "Orphan om"),
                            ("orphan_pamf", "Orphan pamf"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                        ],
                        max_length=16,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "InteropOmReconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orphan_processing_history",
                        to="om.interopomreconciliation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReconciliationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En attente"),
                            ("running", "En cours"),
                            ("succeeded", "Terminé"),
                            ("failed", "Échec"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("queue_task_id", models.CharField(blank=True, max_length=32)),
                ("process_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="om_reconciliation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "permissions": [
                    ("view_om_reconciliation_runs", "Can view OM reconciliation runs")
                ],
            },
        ),
    ]
